In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("C:/Users/sivanand/Desktop/Start-/dataset/online_retail_II.csv")
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

In [3]:
df.describe()

           Quantity         Price    Customer ID
count  1.067371e+06  1.067371e+06  824364.000000
mean   9.938898e+00  4.649388e+00   15324.638504
std    1.727058e+02  1.235531e+02    1697.464450
min   -8.099500e+04 -5.359436e+04   12346.000000
25%    1.000000e+00  1.250000e+00   13975.000000
50%    3.000000e+00  2.100000e+00   15255.000000
75%    1.000000e+01  4.150000e+00   16797.000000
max    8.099500e+04  3.897000e+04   18287.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  object
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 65.1+ MB

In [5]:
df['Customer ID'].is_unique

False

In [6]:
df['Customer ID'].nunique()

5942

In [7]:
df = df.drop(columns=['Customer ID'])
df = df[~df['Invoice'].astype(str).str.startswith('C')]
df = df[df['Quantity'] > 0]
df = df[df['Price'] > 0]
df = df.dropna(subset=['Description'])

In [8]:
df=df.copy()

In [9]:

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df['Revenue']     = df['Quantity'] * df['Price']
df['Year']        = df['InvoiceDate'].dt.year
df['Month']       = df['InvoiceDate'].dt.month

In [10]:
df.describe()

,Quantity,InvoiceDate,Price,Revenue,Year,Month
count,1.041670e+06,1041670,1.041670e+06,1.041670e+06,1.041670e+06,1.041670e+06
mean,1.096346e+01,2011-01-03 16:31:54.300440576,4.076683e+00,2.013363e+01,2.010427e+03,7.506885e+00
min,1.000000e+00,2009-12-01 07:45:00,1.000000e-03,1.000000e-03,2.009000e+03,1.000000e+00
25%,1.000000e+00,2010-07-12 10:28:45,1.250000e+00,3.900000e+00,2.010000e+03,5.000000e+00
50%,3.000000e+00,2010-12-07 15:33:00,2.100000e+00,9.960000e+00,2.010000e+03,8.000000e+00
75%,1.000000e+01,2011-07-24 12:05:00,4.130000e+00,1.770000e+01,2.011000e+03,1.100000e+01
max,8.099500e+04,2011-12-09 12:50:00,2.511109e+04,1.684696e+05,2.011000e+03,1.200000e+01
std,1.265150e+02,NaN,5.144773e+01,2.031165e+02,5.736296e-01,3.525009e+00

In [11]:
print(df.isnull().sum())

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Country        0
Revenue        0
Year           0
Month          0
dtype: int64

In [20]:

df[['Invoice','Description', 'Quantity', 'Price', 'Revenue' , 'Month', 'Year']]

,Invoice,Description,Quantity,Price,Revenue,Month,Year
0,489434,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,6.95,83.40,12,2009
1,489434,PINK CHERRY LIGHTS,12,6.75,81.00,12,2009
2,489434,WHITE CHERRY LIGHTS,12,6.75,81.00,12,2009
3,489434,"RECORD FRAME 7"" SINGLE SIZE",48,2.10,100.80,12,2009
4,489434,STRAWBERRY CERAMIC TRINKET BOX,24,1.25,30.00,12,2009
...,...,...,...,...,...,...,...
1067366,581587,CHILDREN'S APRON DOLLY GIRL,6,2.10,12.60,12,2011
1067367,581587,CHILDRENS CUTLERY DOLLY GIRL,4,4.15,16.60,12,2011
1067368,581587,CHILDRENS CUTLERY CIRCUS PARADE,4,4.15,16.60,12,2011
1067369,581587,BAKING SET 9 PIECE RETROSPOT,3,4.95,14.85,12,2011
1067370,581587,POSTAGE,1,18.00,18.00,12,2011